import type { Metadata } from "next";

import "./globals.css";
import Navbar from "./Components/Navbar";
import Category from "./Components/Category";
import Marquee from "./Components/Marquee";

import { Noto_Serif_Bengali } from "next/font/google";
import { Noto_Sans_Bengali } from "next/font/google";
import Footer from "./Components/Footer";
import { Toaster } from "react-hot-toast";
import { Hind_Siliguri } from "next/font/google";

const notoSansBengali = Noto_Sans_Bengali({
  variable: "--font-noto-sans-bengali",
  subsets: ["latin", "bengali"],
});
const notoSerifBengali = Noto_Serif_Bengali({
  variable: "--font-noto-serif-bengali",
  subsets: ["latin", "bengali"],
});

const hindSiliguri = Hind_Siliguri({
  subsets: ["bengali", "latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-hind-siliguri",
  display: "swap",
});


export const metadata: Metadata = {
  title: "বাজার দর",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en" data-theme="light"
      className={` ${notoSansBengali.variable} ${notoSerifBengali.variable} ${hindSiliguri.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#f2f6f3]">
        
        <Navbar/>
        <Category/>
        <Marquee/>
        <main>

        {children}
        </main>
        <Footer/>
        <Toaster position="top-center"  />
        </body>
    </html>
  );
}
